# docker-compose.yml
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jobtracker
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -proot || exit 1"]
      interval: 5s
      retries: 30

  api:
    build: ./api
    environment:
      DATABASE_URL: mysql+pymysql://root:root@db:3306/jobtracker
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy


  web:
    build: ./web
    command: ["npm","run","dev","--","--host","0.0.0.0"]
    environment:
      VITE_API_URL: http://localhost:8000/graphql
    volumes:
      - ./web:/usr/src/app
    ports:
      - "5173:5173"
    depends_on:
       - api